version: '3.8'

services:
  db:
    image: postgres:17
    container_name: fin_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fin_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 
